logLevel = "$LOG_LEVEL"

defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  
  [entryPoints.api]
    address = ":8080"

[api]
  entryPoint = "api"
  dashboard = true

[ecs]
  clusters = ["$CLUSTER"]
  watch = true
  autoDiscoverClusters = false
  refreshSeconds = 15
  exposedByDefault = false
  region = "$AWS_REGION"

[acme]
  email = "$EMAIL"
  storage = "/acme/acme.json"
  entryPoint = "https"
  onHostRule = true
  caServer = "$CA_SERVER"

[acme.dnsChallenge]
  provider = "route53"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "$DOMAIN"

[ping]
  entryPoint = "http"
